# Generated by Django 2.1.5 on 2019-02-18 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permitidos',
            options={'verbose_name_plural': 'Permitidos'},
        ),
    ]
