# Generated by Django 3.1.6 on 2021-08-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190218_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitidos',
            name='estagiario',
            field=models.BooleanField(default=False),
        ),
    ]
