# Generated by Django 2.1.5 on 2019-02-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='jornada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
