# Generated by Django 2.1.5 on 2019-02-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0004_remove_periodo_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='jornada_trab',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
