# Generated by Django 2.1.5 on 2019-02-12 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0005_periodo_jornada_trab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='jornada_trab',
        ),
    ]
