# Generated by Django 2.1.5 on 2019-02-12 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0007_periodo_jornada_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='jornada_t',
        ),
    ]
