# Generated by Django 2.1.5 on 2019-02-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0008_remove_periodo_jornada_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='jornada_t',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
