# Generated by Django 2.1.5 on 2019-02-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0011_remove_periodo_jornada_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='jornada_trab',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
