# Generated by Django 2.1.5 on 2019-02-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0012_periodo_jornada_trab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='jornada_trab',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
