# Generated by Django 2.1.5 on 2019-02-12 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0013_auto_20190212_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='jornada_trab',
        ),
    ]
