# Generated by Django 2.1.5 on 2019-02-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0016_auto_20190214_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
