# Generated by Django 2.1.5 on 2019-02-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0017_periodo_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='jornada_dia',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=50, null=True),
        ),
    ]
