# Generated by Django 2.1.5 on 2019-02-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0018_periodo_jornada_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='jornada_dia',
        ),
        migrations.AddField(
            model_name='periodo',
            name='horas',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
