# Generated by Django 2.1.5 on 2019-02-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0019_auto_20190214_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodo',
            old_name='horas',
            new_name='jornada',
        ),
    ]
