# Generated by Django 2.1.5 on 2019-02-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0020_auto_20190214_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='data_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodo',
            name='desligado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='periodo',
            name='dias_corridos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodo',
            name='dias_trabalhados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodo',
            name='media_h_d_c',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='periodo',
            name='media_h_d_t',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
