# Generated by Django 2.1.5 on 2019-02-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0022_auto_20190216_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='media_h_d_t',
        ),
        migrations.AddField(
            model_name='periodo',
            name='horas_totais',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='periodo',
            name='observacoes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
