# Generated by Django 2.1.5 on 2019-02-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0023_auto_20190216_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='media_h_d_t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='dias_corridos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='horas_totais',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
    ]
