# Generated by Django 2.1.5 on 2019-02-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0024_auto_20190218_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='observacoes',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
