# Generated by Django 2.1.5 on 2019-02-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0025_auto_20190218_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodo',
            old_name='observacoes',
            new_name='obs',
        ),
    ]
