# Generated by Django 2.1.5 on 2019-02-18 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0026_auto_20190218_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodo',
            old_name='obs',
            new_name='observacoes',
        ),
    ]
