# Generated by Django 2.1.5 on 2019-02-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0028_entraram'),
    ]

    operations = [
        migrations.AddField(
            model_name='entraram',
            name='display',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
