# Generated by Django 2.1.5 on 2019-02-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0030_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='display',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
