# Generated by Django 3.2.8 on 2021-10-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0033_auto_20190228_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='ip_saida',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
